version: '3.8'

services:
  app:
    build: ./app
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/frontend/src
      - ./frontend/public:/frontend/public
    ports:
      - "3000:3000"
    command: npm start

volumes:
  app:
  frontend:
